### ISSUE TITLE
custom documents

### ISSUE THREAD

**Issue by dangfutures** [VikParuchuri/textbook_quality#1]
Can this work with custom documents not just urls??

**Comment by VikParuchuri** [comment]
For retrieval?  You can write a custom retrieval backend to retrieve from documents, like pdfs or txt files.  The current retrieval services are in `services/adapators`.  I may take a look into writing this myself in the future, but it doesn't exist now.  (although it wouldn't be very difficult to add)

**Comment by VikParuchuri** [comment]
I just pushed an experimental feature to the dev branch that enables using a custom search service for retrieval.  You basically send it a query, and it returns a match.  Very flexible in terms of how you host/include documents.
